packages:
  - 'services/*'
  - 'apps/*'
  - 'packages/*'

allowBuilds:
  '@nestjs/core': true
  '@prisma/client': set this to true or false
  '@prisma/engines': set this to true or false
  msgpackr-extract: set this to true or false
  prisma: set this to true or false
  unrs-resolver: true

onlyBuiltDependencies:
  - "@prisma/client"
  - "prisma"
  - "msgpackr-extract"
  - "@prisma/engines"
